plugins {
    id "java"
    id "maven-publish"
    id "org.springframework.boot" version "3.5.3"
    id "io.spring.dependency-management" version "1.1.7"
}

group = "${properties.group}"
version = "${properties.version}"

if ("${properties.snapshot}" == "true") {
    version = "${project.version}-SNAPSHOT"
}

repositories {
    mavenCentral()
    maven {
        name = "HyperPaint"
        url = "https://maven.hyperpaint.tw1.ru/maven2/"
        credentials {
            username = "${hyperpaint_maven_username}"
            password = "${hyperpaint_maven_password}"
        }
    }
}

dependencies {
    // Spring
    implementation "org.springframework.boot:spring-boot-starter:${spring_version}"
    implementation "org.springframework.boot:spring-boot-starter-web:${spring_version}"
    testImplementation "org.springframework.boot:spring-boot-starter-test:${spring_version}"

    // Lombok
    compileOnly "org.projectlombok:lombok:${project.lombok_version}"
    testCompileOnly "org.projectlombok:lombok:${project.lombok_version}"
    annotationProcessor "org.projectlombok:lombok:${project.lombok_version}"
    testAnnotationProcessor "org.projectlombok:lombok:${project.lombok_version}"

    // ZQL
    implementation "org.antlr:antlr4-runtime:${antlr_version}"

    // ZooKeeper
    implementation "org.apache.curator:curator-framework:${project.curator_version}"

    // Fast util
    implementation "it.unimi.dsi:fastutil:${project.fast_util_version}"

    // Test
    testImplementation "org.junit.jupiter:junit-jupiter:${project.junit_jupiter_version}"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher:${project.junit_platform_version}"

    // Test containers
    testImplementation "org.testcontainers:testcontainers:${project.testcontainers_version}"
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.group}-${project.name}"}
    }
}

test {
    useJUnitPlatform()
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = "${project.group}"
            artifactId = "${project.name}"
            version = "${project.version}"
            from components.java
        }
    }

    repositories {
        maven {
            name = "HyperPaint"
            url = "https://maven.hyperpaint.tw1.ru/maven2/"
            credentials {
                username = "${hyperpaint_maven_username}"
                password = "${hyperpaint_maven_password}"
            }
        }
    }
}