org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Spring
spring_version=3.5.3

# Lombok
lombok_version=1.18.38

# Logger
logger_version=2.25.3

# ANTLR
antlr_version=4.13.2

# Curator
curator_version=5.9.0

# ZooKeeper
zookeeper_version=3.9.4

# JSON Path
json_path_version=2.9.0

# Bouncy Castle
bouncy_castle_version=1.83

# Byte Buddy
byte_buddy_version=1.18.8

# Test
junit_jupiter_version=5.12.0
junit_platform_version=1.12.0

# Test containers
testcontainers_version=1.21.3
