org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Spring
spring_version=3.5.3

# Lombok
lombok_version=1.18.38

# ANTLR
antlr_version=4.13.2

# ZooKeeper
zookeeper_version=3.9.4

# Json Path
json_path_version=2.9.0

# Test
junit_jupiter_version=5.12.0
junit_platform_version=1.12.0

# Test containers MySQL & ZooKeeper
testcontainers_version=1.21.3
