plugins {
    id "java"
    id "org.springframework.boot" version "3.5.3"
    id "io.spring.dependency-management" version "1.1.7"
}

group = "hyperpaint"
version = "1.2.0"

repositories {
    mavenCentral()
    maven {
        url 'https://repo.spongepowered.org/maven/'
    }
}

dependencies {
    implementation project(":zql-exec")

    // Lombok
    compileOnly "org.projectlombok:lombok:${lombok_version}"
    testCompileOnly "org.projectlombok:lombok:${lombok_version}"
    annotationProcessor "org.projectlombok:lombok:${lombok_version}"
    testAnnotationProcessor "org.projectlombok:lombok:${lombok_version}"

    // Spring
    implementation "org.springframework.boot:spring-boot-starter:${spring_version}"
    implementation "org.springframework.boot:spring-boot-starter-web:${spring_version}"
    testImplementation "org.springframework.boot:spring-boot-starter-test:${spring_version}"

    // Curator
    implementation "org.apache.curator:curator-framework:${curator_version}"

    // Bouncy Castle
    implementation "org.bouncycastle:bcpkix-jdk18on:${bouncy_castle_version}"

    // Test
    testImplementation "org.junit.jupiter:junit-jupiter:${junit_jupiter_version}"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher:${junit_platform_version}"

    // Test containers
    testImplementation "org.testcontainers:testcontainers:${testcontainers_version}"
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

test {
    useJUnitPlatform()
}
