zookeeper-exporter:
  zookeeper:
    connectionString: 127.0.0.1:2181
    retryPolicy:
      sleepTimeMilliseconds: 100
      maxRetries: 3
  exporter:
    listen: 0.0.0.0:9141
    metrics:
      - |
        json (
          get (
            list (/path/to/znode) like (textRegex)
          ) labels (
            textPathRegex
          )
        ) value (
          textQuery
        ) labels (
          queryLabel1,
          queryLabel2,
          queryLabel3
        );

# get (znode)
# get (znode) labels (regex)

# list (znode)
# list (znode) like (regex)

# cnt (object)
# sum (object)
# avg (object)
# max (object)
# min (object)

# json (json) value (query)
# json (json) value (query) labels (query...)

# yaml (yaml) value (query)
# yaml (yaml) value (query) labels (query...)
