zql-exporter:
  zookeeper:
    host: 127.0.0.1
    port: 2181
    timeout: 10000
    ssl:
      enabled: false
      # Не обязательны при enabled: false
      key-store-location: keystore.jks
      key-store-password: password
      trust-store-location: truststore.jks
      trust-store-password: password
      hostname-verification: true
  exporter:
    listen: 0.0.0.0:9141
    metrics:


# get (znode)
# get (znode) labels (regex)

# list (znode)
# list (znode) like (regex)

# cnt (object)
# sum (object)
# avg (object)
# max (object)
# min (object)

# json (json) value (query)
# json (json) value (query) labels (query...)

# yaml (yaml) value (query)
# yaml (yaml) value (query) labels (query...)
