zql-exporter:
  zookeeper:
    host: 127.0.0.1
    port: 2181
    timeout:
      session: 10000
      connection: 10000
    ssl:
      enabled: false
      # Не обязательны при enabled: false
      key-store-location: keystore.jks
      key-store-password: password
      trust-store-location: truststore.jks
      trust-store-password: password
      hostname-verification: true
  exporter:
    metrics:

logging:
  level:
    root: "info"
    hyperpaint.zql: "debug"
    org.apache.zookeeper: "warn"
